### PR TITLE
Changes to the UI

### PR DESCRIPTION
**Pull request by SankalpaFernando**
Signed-off-by: Sankalpa Fernando <sankalpafernando2017@gmail.com>
Made the changes to the tiles using Material UI color palette. Meantime did some changes to the font-size because the font size was too small.

### CODE REVIEW

**Comment by SankalpaFernando** [comment]
Could you please add hacktoberfest label to the repo or add "hacktoberfest-accepted" label to this PR

**Comment by thepmsquare** [comment]
i added the label to the PR, ill merge after checking it.

**Comment by thepmsquare** [comment]
looks really great :) but the tiles all have white background after 2048. cant we just repeat the same colors? @SankalpaFernando

**Comment by thepmsquare** [comment]
also the large text size makes the tiles not square on small devices

**Comment by SankalpaFernando** [comment]
@thepmsquare  You were right. Those font-sizes made some changes to the responsiveness of the  UI.

**Pull request merged**
